name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Repo checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: ACR login (using sudo)
      - name: ACR Login
        run: az acr login --name AcrTemp1


      # Step 4: Build Docker Image (using sudo)
      - name: Push image to ACR
        run: |
          docker push AcrTemp1.azurecr.io/myapp:latest

      # Step 5: Push Docker Image to ACR (using sudo)
      - name: Push Docker Image
        run: sudo docker push AcrTemp1.azurecr.io/myapp:latest
