name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Repo checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: ACR login
      - name: ACR Login
        run: az acr login --name acrtemp1

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t acrtemp1.azurecr.io/myapp:latest .

      # Step 5: Push Docker Image to ACR
      - name: Push Docker Image
        run: |
          docker push acrtemp1.azurecr.io/myapp:latest
